-- AlterTable
ALTER TABLE "HomepageContent" ADD COLUMN "showHighlights" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "highlightsTitle" TEXT NOT NULL DEFAULT 'أبرز ما في المنصة',
ADD COLUMN "highlightsTitleEn" TEXT DEFAULT 'Platform Highlights',
ADD COLUMN "highlightsTitleUr" TEXT,
ADD COLUMN "showStats" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "stat1Value" TEXT NOT NULL DEFAULT '2,500+',
ADD COLUMN "stat1Label" TEXT NOT NULL DEFAULT 'مشاريع منجزة',
ADD COLUMN "stat1LabelEn" TEXT DEFAULT 'Completed projects',
ADD COLUMN "stat1LabelUr" TEXT,
ADD COLUMN "stat2Value" TEXT NOT NULL DEFAULT '1,800+',
ADD COLUMN "stat2Label" TEXT NOT NULL DEFAULT 'مقاولون موثوقون',
ADD COLUMN "stat2LabelEn" TEXT DEFAULT 'Verified contractors',
ADD COLUMN "stat2LabelUr" TEXT,
ADD COLUMN "stat3Value" TEXT NOT NULL DEFAULT '10,000+',
ADD COLUMN "stat3Label" TEXT NOT NULL DEFAULT 'خامات',
ADD COLUMN "stat3LabelEn" TEXT DEFAULT 'Materials',
ADD COLUMN "stat3LabelUr" TEXT,
ADD COLUMN "stat4Value" TEXT NOT NULL DEFAULT '3,200+',
ADD COLUMN "stat4Label" TEXT NOT NULL DEFAULT 'عطاءات ممنوحة',
ADD COLUMN "stat4LabelEn" TEXT DEFAULT 'Awarded bids',
ADD COLUMN "stat4LabelUr" TEXT,
ADD COLUMN "showVideosSection" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "videosSectionTitle" TEXT NOT NULL DEFAULT 'اكتشف المنصة',
ADD COLUMN "videosSectionTitleEn" TEXT DEFAULT 'Discover the Platform',
ADD COLUMN "videosSectionTitleUr" TEXT,
ADD COLUMN "showFooter" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "footerAbout" TEXT,
ADD COLUMN "footerAboutEn" TEXT,
ADD COLUMN "footerAboutUr" TEXT,
ADD COLUMN "footerEmail" TEXT DEFAULT 'info@abc-constructions.com',
ADD COLUMN "footerPhone" TEXT DEFAULT '+966 50 000 0000',
ADD COLUMN "footerAddress" TEXT DEFAULT 'الرياض، المملكة العربية السعودية',
ADD COLUMN "footerAddressEn" TEXT DEFAULT 'Riyadh, Saudi Arabia',
ADD COLUMN "footerAddressUr" TEXT;
