export const CoreErrors = {
  CORE_USER_NOT_FOUND: 'CORE_USER_NOT_FOUND',
  CORE_USER_ALREADY_EXISTS: 'CORE_USER_ALREADY_EXISTS',
  CORE_USER_UNAUTHORIZED: 'CORE_USER_UNAUTHORIZED',
  CORE_USER_FORBIDDEN: 'CORE_USER_FORBIDDEN',
  CORE_ORG_NOT_FOUND: 'CORE_ORG_NOT_FOUND',
  CORE_ORG_LIMIT_REACHED: 'CORE_ORG_LIMIT_REACHED',
  CORE_ROLE_NOT_FOUND: 'CORE_ROLE_NOT_FOUND',
  CORE_PERMISSION_DENIED: 'CORE_PERMISSION_DENIED',
  CORE_SESSION_EXPIRED: 'CORE_SESSION_EXPIRED',
  CORE_INVALID_CREDENTIALS: 'CORE_INVALID_CREDENTIALS',
  CORE_MFA_REQUIRED: 'CORE_MFA_REQUIRED',
  CORE_MFA_INVALID: 'CORE_MFA_INVALID',
} as const;
