export const EntityRegistryErrors = {
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  ENTITY_ALREADY_EXISTS: 'ENTITY_ALREADY_EXISTS',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ENTITY_REQUIRED: 'PROFILE_ENTITY_REQUIRED',
  PROFILE_FORBIDDEN: 'PROFILE_FORBIDDEN',
  INTERACTION_ENTITY_REQUIRED: 'INTERACTION_ENTITY_REQUIRED',
  VALIDATION_ENTITY_REQUIRED: 'VALIDATION_ENTITY_REQUIRED',
  RELATIONSHIP_SELF_REFERENCE: 'RELATIONSHIP_SELF_REFERENCE',
  RELATIONSHIP_ENTITY_NOT_FOUND: 'RELATIONSHIP_ENTITY_NOT_FOUND',
  CONSENT_ENTITY_REQUIRED: 'CONSENT_ENTITY_REQUIRED',
} as const;
