export const FinancialErrors = {
  FINANCIAL_RESERVATION_NOT_FOUND: 'FINANCIAL_RESERVATION_NOT_FOUND',
  FINANCIAL_RESERVATION_INVALID_TRANSITION: 'FINANCIAL_RESERVATION_INVALID_TRANSITION',
  FINANCIAL_RESERVATION_CANNOT_MODIFY: 'FINANCIAL_RESERVATION_CANNOT_MODIFY',
  FINANCIAL_RESERVATION_CANNOT_DELETE: 'FINANCIAL_RESERVATION_CANNOT_DELETE',
  FINANCIAL_RESERVATION_EXCEEDS_TOTAL: 'FINANCIAL_RESERVATION_EXCEEDS_TOTAL',
  FINANCIAL_RESERVATION_NO_FUNDS: 'FINANCIAL_RESERVATION_NO_FUNDS',
  FINANCIAL_RELEASE_NOT_FOUND: 'FINANCIAL_RELEASE_NOT_FOUND',
  FINANCIAL_INSUFFICIENT_HELD: 'FINANCIAL_INSUFFICIENT_HELD',
} as const;
