export const GeneralErrors = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_MAX_LENGTH: 'VALIDATION_MAX_LENGTH',
  VALIDATION_MIN_VALUE: 'VALIDATION_MIN_VALUE',
  VALIDATION_MAX_VALUE: 'VALIDATION_MAX_VALUE',
  VALIDATION_UNIQUE_CONSTRAINT: 'VALIDATION_UNIQUE_CONSTRAINT',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;
