export const InvoicingErrors = {
  INVOICING_INVOICE_NOT_FOUND: 'INVOICING_INVOICE_NOT_FOUND',
  INVOICING_INVOICE_INVALID_TRANSITION: 'INVOICING_INVOICE_INVALID_TRANSITION',
  INVOICING_INVOICE_ALREADY_SUBMITTED: 'INVOICING_INVOICE_ALREADY_SUBMITTED',
  INVOICING_INVOICE_CANNOT_MODIFY: 'INVOICING_INVOICE_CANNOT_MODIFY',
  INVOICING_INVOICE_CANNOT_DELETE: 'INVOICING_INVOICE_CANNOT_DELETE',
  INVOICING_PURCHASE_ORDER_NOT_FOUND: 'INVOICING_PURCHASE_ORDER_NOT_FOUND',
  INVOICING_INVOICE_ITEM_REQUIRED: 'INVOICING_INVOICE_ITEM_REQUIRED',
  INVOICING_MATCH_NOT_FOUND: 'INVOICING_MATCH_NOT_FOUND',
  INVOICING_MISMATCH_DETECTED: 'INVOICING_MISMATCH_DETECTED',
  INVOICING_INVOICE_ALREADY_MATCHED: 'INVOICING_INVOICE_ALREADY_MATCHED',
  INVOICING_INVOICE_NOT_MATCHED: 'INVOICING_INVOICE_NOT_MATCHED',
  INVOICING_CANNOT_AUTHORIZE: 'INVOICING_CANNOT_AUTHORIZE',
} as const;