export const QualityErrors = {
  QUALITY_INSPECTION_NOT_FOUND: 'QUALITY_INSPECTION_NOT_FOUND',
  QUALITY_INSPECTION_INVALID_TRANSITION: 'QUALITY_INSPECTION_INVALID_TRANSITION',
  QUALITY_INSPECTION_CANNOT_MODIFY: 'QUALITY_INSPECTION_CANNOT_MODIFY',
  QUALITY_INSPECTION_CANNOT_DELETE: 'QUALITY_INSPECTION_CANNOT_DELETE',
  QUALITY_INSPECTION_ITEM_NOT_FOUND: 'QUALITY_INSPECTION_ITEM_NOT_FOUND',
  QUALITY_NCR_NOT_FOUND: 'QUALITY_NCR_NOT_FOUND',
  QUALITY_CERTIFICATE_NOT_FOUND: 'QUALITY_CERTIFICATE_NOT_FOUND',
  QUALITY_ATTACHMENT_NOT_FOUND: 'QUALITY_ATTACHMENT_NOT_FOUND',
} as const;
