export const SupplierNetworkErrors = {
  SUPPLIER_PROFILE_NOT_FOUND: 'SUPPLIER_PROFILE_NOT_FOUND',
  SUPPLIER_PROFILE_ALREADY_EXISTS: 'SUPPLIER_PROFILE_ALREADY_EXISTS',
  SUPPLIER_PROFILE_INVALID_TRANSITION: 'SUPPLIER_PROFILE_INVALID_TRANSITION',
  SUPPLIER_DOCUMENT_NOT_FOUND: 'SUPPLIER_DOCUMENT_NOT_FOUND',
  SUPPLIER_CERTIFICATION_NOT_FOUND: 'SUPPLIER_CERTIFICATION_NOT_FOUND',
  SUPPLIER_BANKING_NOT_FOUND: 'SUPPLIER_BANKING_NOT_FOUND',
  SUPPLIER_CAPABILITY_NOT_FOUND: 'SUPPLIER_CAPABILITY_NOT_FOUND',
  SUPPLIER_CAPABILITY_ALREADY_EXISTS: 'SUPPLIER_CAPABILITY_ALREADY_EXISTS',
  SUPPLIER_RELATIONSHIP_NOT_FOUND: 'SUPPLIER_RELATIONSHIP_NOT_FOUND',
  SUPPLIER_RELATIONSHIP_ALREADY_EXISTS: 'SUPPLIER_RELATIONSHIP_ALREADY_EXISTS',
  SUPPLIER_RATING_NOT_FOUND: 'SUPPLIER_RATING_NOT_FOUND',
  SUPPLIER_ORGANIZATION_MISMATCH: 'SUPPLIER_ORGANIZATION_MISMATCH',
} as const;
