export const SurveyErrors = {
  SURVEY_SECTION_NOT_FOUND: 'SURVEY_SECTION_NOT_FOUND',
  SURVEY_QUESTION_NOT_FOUND: 'SURVEY_QUESTION_NOT_FOUND',
  SURVEY_QUESTION_VALIDATION: 'SURVEY_QUESTION_VALIDATION',
  SURVEY_QUESTION_HAS_RESPONSES: 'SURVEY_QUESTION_HAS_RESPONSES',
  SURVEY_INVALID_ORDER: 'SURVEY_INVALID_ORDER',
} as const;