export const TendersErrors = {
  TENDERS_TENDER_NOT_FOUND: 'TENDERS_TENDER_NOT_FOUND',
  TENDERS_TENDER_EXPIRED: 'TENDERS_TENDER_EXPIRED',
  TENDERS_TENDER_ALREADY_AWARDED: 'TENDERS_TENDER_ALREADY_AWARDED',
  TENDERS_BID_NOT_FOUND: 'TENDERS_BID_NOT_FOUND',
  TENDERS_BID_EXPIRED: 'TENDERS_BID_EXPIRED',
} as const;
