export const WorkflowErrors = {
  WORKFLOW_DEFINITION_NOT_FOUND: 'WORKFLOW_DEFINITION_NOT_FOUND',
  WORKFLOW_INSTANCE_NOT_FOUND: 'WORKFLOW_INSTANCE_NOT_FOUND',
  WORKFLOW_INVALID_TRANSITION: 'WORKFLOW_INVALID_TRANSITION',
  WORKFLOW_STEP_NOT_ASSIGNED: 'WORKFLOW_STEP_NOT_ASSIGNED',
} as const;
